/*
 * MLSensor — ESP Fault Classifier
 * ESP32 DevKit V1 deployment
 * Serial output at 115200 baud
 *
 * Files required in sketch folder:
 *   esp_classifier.h  — Random Forest model (generated by micromlgen)
 *   esp_scaler.h      — StandardScaler parameters
 *   esp_features.h    — Feature extraction functions
 */
#include "esp_scaler.h"
#include "esp_features.h"
#include "esp_classifier.h"

/* ── Sensor data buffer ──────────────────────────────────────
 * In real deployment: filled by ADC readings every 100ms
 * Here: filled with representative test vectors per fault class
 * Each row = one timestep, columns = [I, omega, Q, H, vib, slip]
 * ──────────────────────────────────────────────────────────── */
Eloquent::ML::Port::RandomForest classifier;
float sensor_window[WINDOW_SIZE][N_SIGNALS];

/* ── Test vectors from simulation operating point ────────────
 * Values match steady-state results from OpenModelica:
 *   Normal:   omega=183.5, I=14.73, Q=0.0100, slip=0.0267
 *   Gas Lock: omega=186.5, I=14.12, Q=0.0108, slip=0.0083
 *   Erosion:  omega=184.2, I=14.65, Q=0.0088, slip=0.0245
 *   Friction: omega=181.0, I=15.05, Q=0.0098, slip=0.0385
 * ──────────────────────────────────────────────────────────── */
// ── Representative test vectors from training data ──
// Copy these into MLSensor.ino to replace the hardcoded values

// ── Representative test vectors from training data ──
// Copy these into MLSensor.ino to replace the hardcoded values

void load_normal(void) {
    // Source: simulation t=263.8s, label=Normal
    float data[WINDOW_SIZE][N_SIGNALS] = {
        {14.722401f, 184.984342f, 0.009845f, 40.491894f, 0.045174f, 0.029677f},
        {14.622294f, 183.378106f, 0.009905f, 40.288100f, -0.015267f, 0.030343f},
        {14.826166f, 182.842304f, 0.009865f, 40.373051f, 0.094960f, 0.029568f},
        {14.784488f, 182.517718f, 0.010361f, 40.346006f, 0.051877f, 0.029824f},
        {14.795145f, 182.510596f, 0.009999f, 39.562236f, 0.006821f, 0.030891f},
        {14.642437f, 185.209858f, 0.010098f, 39.622238f, 0.074063f, 0.028273f},
        {14.398341f, 184.349417f, 0.009660f, 40.099693f, 0.009728f, 0.029327f},
        {14.885915f, 181.963150f, 0.009844f, 40.155213f, 0.102371f, 0.029814f},
        {14.649516f, 182.003584f, 0.009937f, 40.077470f, 0.033481f, 0.028807f},
        {14.591926f, 183.573004f, 0.010480f, 39.970781f, 0.094075f, 0.030309f},
        {14.825364f, 182.434677f, 0.010026f, 39.858271f, 0.088638f, 0.028356f},
        {14.662540f, 183.199081f, 0.010021f, 40.015516f, 0.084050f, 0.029563f},
        {14.880332f, 185.004161f, 0.009811f, 40.170117f, 0.116477f, 0.031057f},
        {14.813893f, 184.520556f, 0.009959f, 39.294377f, -0.053442f, 0.029247f},
        {14.823877f, 181.739759f, 0.009960f, 39.613092f, 0.108046f, 0.028970f},
        {14.516449f, 182.440022f, 0.010306f, 39.998245f, 0.087522f, 0.030790f},
        {14.903134f, 183.696834f, 0.009619f, 39.842557f, 0.023033f, 0.028449f},
        {14.760530f, 184.580906f, 0.009739f, 40.068679f, 0.107543f, 0.031401f},
        {14.665950f, 182.629274f, 0.010124f, 40.713033f, 0.069541f, 0.029618f},
        {14.742850f, 183.819665f, 0.010237f, 40.256630f, 0.012668f, 0.028670f}
    };
    memcpy(sensor_window, data, sizeof(data));
}

void load_gas_lock(void) {
    // Source: simulation t=298.8s, label=Gas Lock
    float data[WINDOW_SIZE][N_SIGNALS] = {
        {14.785881f, 185.260171f, 0.010132f, 39.932498f, 0.389541f, 0.022643f},
        {14.539389f, 184.522729f, 0.009905f, 39.596376f, 0.356830f, 0.022679f},
        {14.680268f, 184.148944f, 0.010535f, 40.045136f, 0.494547f, 0.021790f},
        {15.047180f, 184.590716f, 0.010214f, 40.202709f, 0.407559f, 0.023606f},
        {14.489256f, 182.886262f, 0.010405f, 40.145484f, 0.372292f, 0.020397f},
        {14.754881f, 182.957848f, 0.010074f, 39.811098f, 0.418935f, 0.021522f},
        {14.627229f, 184.008341f, 0.010735f, 40.245449f, 0.420249f, 0.020106f},
        {14.781675f, 183.734981f, 0.010036f, 39.979676f, 0.372597f, 0.021121f},
        {14.865731f, 185.578755f, 0.009929f, 39.930856f, 0.428895f, 0.020469f},
        {14.617705f, 186.188502f, 0.010508f, 39.676773f, 0.503752f, 0.020251f},
        {14.843477f, 185.253453f, 0.010006f, 39.906377f, 0.368549f, 0.021531f},
        {15.008821f, 183.031954f, 0.010512f, 39.468569f, 0.410404f, 0.019898f},
        {14.685582f, 183.518888f, 0.010376f, 40.345930f, 0.389457f, 0.022818f},
        {14.793374f, 185.278822f, 0.009924f, 39.792758f, 0.409910f, 0.021944f},
        {14.587074f, 184.756972f, 0.010610f, 40.708908f, 0.336221f, 0.021715f},
        {14.678529f, 183.072074f, 0.010290f, 39.725559f, 0.444493f, 0.021928f},
        {14.649139f, 184.071333f, 0.010246f, 40.392940f, 0.371014f, 0.019676f},
        {14.795181f, 183.853852f, 0.010400f, 39.791047f, 0.316715f, 0.022751f},
        {14.856342f, 186.385679f, 0.010346f, 40.117907f, 0.388881f, 0.022439f},
        {14.659192f, 185.633935f, 0.010256f, 39.787328f, 0.423994f, 0.020911f}
    };
    memcpy(sensor_window, data, sizeof(data));
}

void load_erosion(void) {
    // Source: simulation t=263.8s, label=Erosion
    float data[WINDOW_SIZE][N_SIGNALS] = {
        {14.712081f, 184.337511f, 0.009425f, 40.458146f, 0.163337f, 0.026489f},
        {14.729108f, 183.717426f, 0.009644f, 40.077460f, 0.120125f, 0.027559f},
        {14.823479f, 183.826015f, 0.009837f, 39.617027f, 0.228167f, 0.024692f},
        {14.549202f, 183.340271f, 0.009474f, 39.823035f, 0.149386f, 0.026111f},
        {14.403429f, 184.019873f, 0.009357f, 39.882446f, 0.156025f, 0.026134f},
        {14.735930f, 185.356030f, 0.009303f, 40.028784f, 0.254489f, 0.025871f},
        {14.762568f, 183.540640f, 0.009192f, 40.082775f, 0.323072f, 0.027491f},
        {14.682583f, 184.376941f, 0.009726f, 40.094869f, 0.257465f, 0.026172f},
        {14.713694f, 183.375702f, 0.009605f, 41.103837f, 0.229756f, 0.027537f},
        {14.841307f, 182.508586f, 0.009342f, 39.859919f, 0.184116f, 0.027302f},
        {14.640670f, 183.815845f, 0.009498f, 40.695609f, 0.194303f, 0.026747f},
        {14.667695f, 185.885816f, 0.009315f, 39.721477f, 0.103686f, 0.026210f},
        {14.721346f, 183.156224f, 0.009709f, 40.164189f, 0.093945f, 0.026995f},
        {14.526518f, 183.005273f, 0.009537f, 39.552659f, 0.228354f, 0.027008f},
        {14.686706f, 183.096232f, 0.009630f, 39.924287f, 0.229078f, 0.027978f},
        {14.699929f, 185.778846f, 0.009494f, 39.894196f, 0.104262f, 0.026524f},
        {14.955047f, 185.077135f, 0.009428f, 40.223673f, 0.208741f, 0.027404f},
        {14.664773f, 184.605482f, 0.009495f, 39.948789f, 0.149925f, 0.026786f},
        {14.739492f, 185.326070f, 0.009500f, 40.061908f, 0.199970f, 0.026396f},
        {14.847283f, 184.878408f, 0.009531f, 39.710954f, 0.221025f, 0.028152f}
    };
    memcpy(sensor_window, data, sizeof(data));
}

void load_friction(void) {
    // Source: simulation t=263.8s, label=Friction
    float data[WINDOW_SIZE][N_SIGNALS] = {
        {14.660089f, 182.502094f, 0.010225f, 39.416637f, 0.328032f, 0.032333f},
        {14.555142f, 182.580847f, 0.010213f, 40.337157f, 0.343079f, 0.033789f},
        {14.602409f, 181.867759f, 0.010249f, 40.381308f, 0.277332f, 0.035001f},
        {14.689511f, 182.835237f, 0.010310f, 39.542719f, 0.261055f, 0.034108f},
        {14.905219f, 182.143585f, 0.010292f, 39.878063f, 0.328930f, 0.033514f},
        {14.647278f, 182.664022f, 0.009701f, 40.367345f, 0.215972f, 0.034219f},
        {14.855069f, 182.548252f, 0.009860f, 39.573527f, 0.266402f, 0.034335f},
        {14.535382f, 182.749551f, 0.009991f, 39.948069f, 0.235812f, 0.033457f},
        {14.253740f, 181.753232f, 0.009995f, 39.926992f, 0.344502f, 0.033719f},
        {14.713598f, 182.207764f, 0.009763f, 40.310185f, 0.307029f, 0.034078f},
        {14.642073f, 182.557845f, 0.009875f, 39.493170f, 0.314272f, 0.031473f},
        {14.601314f, 182.682002f, 0.010102f, 39.869457f, 0.306243f, 0.034203f},
        {14.583747f, 182.724056f, 0.010151f, 40.288992f, 0.294271f, 0.032215f},
        {14.627447f, 183.307344f, 0.009851f, 39.684209f, 0.298700f, 0.034340f},
        {14.585472f, 181.618260f, 0.009907f, 39.958119f, 0.268291f, 0.032130f},
        {14.599064f, 182.448870f, 0.010093f, 40.464942f, 0.312241f, 0.032512f},
        {14.529747f, 181.786822f, 0.009924f, 40.197335f, 0.320142f, 0.031706f},
        {14.414164f, 181.683810f, 0.009587f, 40.211429f, 0.233077f, 0.034287f},
        {14.402163f, 183.065417f, 0.009923f, 39.920869f, 0.330597f, 0.032035f},
        {15.102738f, 182.796400f, 0.009835f, 40.106716f, 0.363499f, 0.033686f}
    };
    memcpy(sensor_window, data, sizeof(data));
}


/* ── Single inference: extract → normalize → predict ─────── */
void run_inference(const char* label, void (*load_fn)(void)) {
    load_fn();

    uint32_t t_start = micros();

    float* fv = extract_features(sensor_window);
    normalize_features(fv, N_FEATURES);
    int pred = classifier.predict(fv);

    uint32_t t_end = micros();
    uint32_t latency_us = t_end - t_start;

    Serial.printf("  %-12s → %-10s  [%4lu us  /  %.2f ms]\n",
                  label,
                  CLASS_NAMES[pred],
                  latency_us,
                  latency_us / 1000.0f);
}

/* ── Arduino setup — runs once ───────────────────────────── */
void setup() {
    Serial.begin(115200);
    delay(500);

    Serial.println();
    Serial.println("========================================");
    Serial.println("  MLSensor — ESP Fault Classifier");
    Serial.printf ("  ESP32 @ %d MHz\n", ESP.getCpuFreqMHz());
    Serial.printf ("  Free heap: %d bytes\n", ESP.getFreeHeap());
    Serial.printf ("  Features: %d  |  Classes: 4\n", N_FEATURES);
    Serial.println("========================================");
    Serial.println();

    Serial.println("--- Validation test: one window per fault class ---");
    run_inference("NORMAL",   load_normal);
    run_inference("GAS_LOCK", load_gas_lock);
    run_inference("EROSION",  load_erosion);
    run_inference("FRICTION", load_friction);
    Serial.println();
    Serial.println("--- Entering continuous inference loop ---");
    Serial.println("    (Replace load functions with real sensor ADC reads)");
    Serial.println();
}

/* ── Arduino loop — continuous inference ─────────────────── */
void loop() {
    static uint32_t count = 0;
    static uint32_t total_latency = 0;

    /* Rotate through all four fault classes */
  switch (count % 4) {
      case 0: load_normal();   break;
      case 1: load_gas_lock(); break;   // ← add underscore
      case 2: load_erosion();  break;
      case 3: load_friction(); break;
  }
    uint32_t t0 = micros();
    float* fv = extract_features(sensor_window);
    normalize_features(fv, N_FEATURES);
    int pred = classifier.predict(fv);
    uint32_t latency = micros() - t0;

    total_latency += latency;

    Serial.printf("[%05lu] %-10s  %4lu us",
                  count, CLASS_NAMES[pred], latency);

    /* Print rolling average latency every 20 inferences */
    if ((count + 1) % 20 == 0) {
        Serial.printf("   (avg: %.0f us)", (float)total_latency / 20.0f);
        total_latency = 0;
    }
    Serial.println();

    count++;
    delay(100);   /* 100ms stride = 10 Hz inference rate */
}